<?php
/**
 * Orange Cat
 * Copyright (C) 2018 Orange Cat
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html
 *
 * @category Orangecat
 * @package Orangecat_Featureds
 * @copyright Copyright (c) 2018 Orange Cat
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Oliverio Gombert <olivertar@gmail.com>
 */
?>
<?php
if ($exist = ($block->getFeaturedProduct())) {
     $collection = $block->getFeaturedProduct();
     $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
     $_helper = $this->helper('Magento\Catalog\Helper\Output');
     $viewMode = 'grid';
     $showDescription = false;
     $pos = false;
     $type = 'widget-featured-grid';
     $image = 'category_page_grid';
     $title = $block->getData('info')->getTitle();
}
?>
<?php if ($exist): ?>
<div class="block widget block-featured-products <?php echo $viewMode; ?>">
     
     <div class="content-heading">
        <h2 class="title"><?php echo $title; ?></h2>
     </div>
     
     <div class="block-content">
     <div class="products wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
          <ol class="products list items product-items">
          <?php $iterator = 1; ?>
          <?php foreach ($collection as $_product):?>
          <?php echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">';?>
               <div class="product-item-info" data-container="product-grid">
               <?php
                $productImage = $block->getImage($_product, $image);
               if ($pos != null) {
                    $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"';
                }
               ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                    <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>">
                            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php echo $block->getProductPrice($_product)?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                        <div class="product-item-inner">
                             <div class="product actions product-item-actions"
                             <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                  <div class="actions-primary"
                                  <?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                  <?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                  <form data-role="tocart-form" action="<?php echo $block->escapeHtml($postParams['action']); ?>" method="post">
                                       <input type="hidden" name="product" value="<?php echo $block->escapeHtml($postParams['data']['product']); ?>">
                                       <input type="hidden" name="<?php echo \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $block->escapeHtml($postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED]); ?>">
                                        <?php echo $block->getBlockHtml('formkey')?>
                                       <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
                                            <span><?php echo __('Add to Cart') ?></span>
                                       </button>
                                  </form>
                                  <?php else : ?>
                                       <?php if ($_product->getIsSalable()): ?>
                                       <div class="stock available">
                                            <span><?php echo __('In stock') ?></span>
                                       </div>
                                       <?php else : ?>
                                       <div class="stock unavailable">
                                            <span><?php echo __('Out of stock') ?></span>
                                       </div>
                                       <?php endif; ?>
                                  <?php endif; ?>
                             </div>
                             <div data-role="add-to-links" class="actions-secondary" <?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                  <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                  <a href="#"
                                              class="action towishlist"
                                              title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                              aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                              data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                              data-action="add-to-wishlist" role="button"> <span><?php echo __('Add to Wish List') ?></span>
                                  </a>
                                  <?php endif; ?>
                                  <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                  <a href="#" class="action tocompare"
                                              title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                              aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                              data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                              role="button"> <span><?php echo __('Add to Compare') ?></span>
                                  </a>
                             </div>
                             <?php if ($showDescription):?>
                             <div class="product description product-item-description">
                                  <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')?>
                                  <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="action more"><?php echo __('Learn More') ?></a>
                             </div>
                             <?php endif; ?>
                        </div>
                  </div>
            </div>
            <?php echo($iterator == count($collection)+1) ? '</li>' : ''?>
        <?php endforeach ?>
        </ol>
    </div>
</div>
</div>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
    <script type="text/x-magento-init">
        { "[data-role=tocart-form], .form.map.checkout": { "catalogAddToCart": {} } }
    </script>
    <?php endif; ?>
<?php endif; ?>